### PR TITLE
Handle dropdown options with only a name

### LINKED ISSUE #214: Dropdown options' names and values incorrectly parsed
I have run into a problem when parsing some PDFs that contain dropdown selects with only a single string value for each option. The old version of pdf.js included in this project simply reports the option list as an array of strings, whereas the newer versions of pdf.js seem to handle this better by automatically converting the options list to an array of arrays, each with the name and value as is expected by pdf2json.

Here's an example dropdown field as supplied to `_addSelect()` in pdffield.js:
```
{
    subtype: 'Widget',
    rect: [ 165.7, 143.4, 322.8, 157.6 ],
    annotationFlags: 4,
    color: [ 0, 0, 0 ],
    borderWidth: 0,
    hasAppearance: true,
    fieldValue: 'Red',
    alternativeText: 'Select from colour spectrum',
    alternativeID: '',
    defaultAppearance: { name: 'ArialMT 11 Tf 0 g' },
    fieldType: 'Ch',
    fieldFlags: 131072,
    fullName: 'Favourite_Colour_List_Box',
    value: [
        'Black',
        'Brown',
        'Red',
        'Orange',
        'Yellow',
        'Green',
        'Blue',
        'Violet',
        'Grey',
        'White'
    ],
    TI: 16
}
```

And here's what it looks like after being added to `formImage.Pages[].Fields`:
```
{
    style: 48,
    T: { Name: 'alpha', TypeInfo: {} },
    id: { Id: 'Favourite_Colour_List_Box', EN: 0 },
    TI: 16,
    AM: 0,
    TU: 'Select from colour spectrum',
    x: 10.356,
    y: 42.775,
    w: 9.319,
    h: 0.888,
    PL: {
        V: [
            'l',
            'r',
            'e',
            'r',
            'e',
            'r',
            'l',
            'i',
            'r',
            'h'
        ],
        D: [
            'B',
            'B',
            'R',
            'O',
            'Y',
            'G',
            'B',
            'V',
            'G',
            'W'
        ]
    },
    V: 'Red'
}
```

Notice the first letter of the colour ends up in the `D` (name) array and the second letter ends up in the `V` (value) array. This is because the `_addSelect()` function is naively accessing the strings in the options as arrays.

### PR DESCRIPTION
**Pull request by cmmcneill**
Added a check for dropdown/select options to handle options with only a name string, instead of an array with name and value pairs.

Fixes #214

### CODE REVIEW

File: lib/pdffield.js [hunk 1]
```diff
@@ -220,6 +220,9 @@ let PDFField = (function PDFFieldClosure() {
         anData.w -= 0.5; //adjust combobox width
         anData.PL = {V: [], D: []};
         _.each(field.value, function(ele, idx) {
+            if (!Array.isArray(ele)) {
+                ele = [ele, ele];
```
Comment (modesty) [inline lib/pdffield.js:224]: don't mutate the iterative object, change it to:
if (!Array.isArray(ele)) {
  anData.PL.D.push([ele, ele]);
}
else {
  anData.PL.D.push(ele[0]);
  anData.PL.V.push(ele[1]);
}
}

**Review by modesty — CHANGES_REQUESTED** [review]

File: lib/pdffield.js (hunk 1 above)
Comment (cmmcneill) [reply lib/pdffield.js:224]: Reassigning `ele` to a new array doesn't mutate anything here, but I'll change it so it's more obvious that this doesn't affect `field.value`.
